import jsPDF from "jspdf";
import { getCompanyUsers } from "../firebase/firebase";

const generatePDF = (jobs) => {
  const pdf = new jsPDF();

  const marginTop = 10;
  const marginBottom = 10;

  pdf.text("Company Details - Report", 20, marginTop);
  pdf.text("Generated by F.M. Asjedh", 20, marginTop + 10);

  jobs.forEach((company) => {
    pdf.addPage();
    let yPos = marginTop;

    // Company Details
    pdf.text(`Company Details---------`, 20, yPos);
    yPos += 10;
    pdf.text(`Name: ${company.displayName}`, 20, yPos);
    yPos += 10;
    pdf.text(`Email: ${company.email}`, 20, yPos);
    yPos += 10;
    pdf.text(`Contact No: ${company.userPhone}`, 20, yPos);
    yPos += 10;
    pdf.text(
      `Address: ${company.address.street}, ${company.address.city}, ${company.address.state}, ${company.address.country}, ${company.address.zip}`,
      20,
      yPos
    );
    yPos += 10;

    pdf.text("-----------------------------", 20, yPos);
    yPos += 10;
  });

  pdf.save("job_report.pdf");
};

export const generateReport = async () => {
  try {
    const company = await getCompanyUsers();

    if (company) {
      generatePDF(company);
    } else {
      console.error("No DETAILS");
    }
  } catch (error) {
    console.error("Error generating report:", error);
  }
};
